#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.{build}
environment:
  gallery_api_key:
    secure: WeDp1yZJECZBjjW+22A8lA8+gmz+wiYostPKtU4pdLXORfK//eJCdR7f0k3oJ+2r

install:
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Install-Module -Name Pester, PSSCriptAnalyzer, PSake -Scope CurrentUser -Force -Verbose

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Import-Module .\VirtualEngine.Build.psd1 -Force
        Invoke-PSake -BuildFile .\Build.PSake.ps1 -TaskList Default
        Write-Verbose "PSake.build_success: $($psake.build_success)" -Verbose
        if (-not $psake.build_success) { exit 1 }

on_finish:
  - ps: |
        Invoke-PSake -BuildFile .\Build.PSake.ps1 -TaskList Appveyor
